# 7월6일

In [2]:
import random
import numpy as np
import pandas as pd
pd.options.display.float_format = '{:.5f}'.format

[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling


In [2]:
# 파이썬 함수
print(random.random(),'\n') # 0.0<= x <1.0 사이 난수(램덤숫자)
print(random.randint(1,10),'\n') # 1<= x <=10 사이 정수중 난수(1,10포함)
print(random.uniform(10,20),'\n') # min,max 사이 float 리턴
print(random.randrange(10),'\n') # 0 < x <10 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소 랜덤 선택
# 리스트 요소 중복 안되게 리턴 random.sample(li,뽑을 숫자 갯수)
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') 
# 리스트 요소를 다시 섞어서 리턴
random.shuffle(li)
print(li)

0.3153092368984526 

1 

11.109540049783135 

5 

5 

[4, 2, 3] 

[3, 5, 1, 2, 4]


In [154]:
# 0 ~ 1사이의 균일분포
r = np.random.rand(100000000) 
# print(r)
r.mean()

0.5000558950887946

In [155]:
# 표준 정규분포
r = np.random.randn(10)
print(r)
r.mean()  # 점점 0에 가까워짐 범위 넓을수록 

[-0.58211075  1.27995893 -1.6742616  -0.69639507 -0.74436789 -0.56847233
  1.57167417  1.50828978  0.72674188 -1.77368963]


-0.0952632511062698

In [156]:
np.random.uniform(1.0,2.0,10)

array([1.61227116, 1.20331492, 1.05564601, 1.81753921, 1.16988135,
       1.82344777, 1.96902356, 1.00455216, 1.93951884, 1.41467065])

In [157]:
# 행렬형태로 뽑기
np.random.uniform(0,1,(2,3))

array([[0.65595545, 0.30124127, 0.50085256],
       [0.67019811, 0.68875136, 0.28115258]])

In [158]:
# 0-1사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.3938847 , 0.80548262, 0.31436184],
       [0.85908758, 0.2393271 , 0.25165715]])

In [159]:
# 배열을 df로 컬럼 이름 넣어서 변환
ar = np.random.rand(4,8)
df = pd.DataFrame(ar,columns=['id','gender','age','region','product','price','qty','time']
)
df

id  gender     age  region  product   price     qty    time
0 0.60122 0.03603 0.72640 0.49979  0.21823 0.65119 0.37438 0.06847
1 0.49060 0.96237 0.00489 0.00890  0.03039 0.78930 0.21699 0.69954
2 0.67952 0.76590 0.00362 0.98821  0.48950 0.24311 0.71509 0.81084
3 0.62169 0.03966 0.80522 0.99918  0.02476 0.72411 0.75817 0.59716

- Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df3를 출력하세요

In [160]:
df['id']= np.random.randint(1000,9999,4)
df['gender']= np.random.choice(['male','female'],4)
df['age']= np.random.randint(1,100,4)
df3 = df[['id','gender','age']]

In [161]:
df3

id  gender  age
0  5696    male    8
1  4854    male   75
2  2156  female    2
3  1356    male   88

In [162]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력(가운데값 출력 의미)
large_ar = np.random.randn(1000)
large_ar.sort()
large_ar[int(0.5*len(large_ar))]

-0.056092353722470636

In [163]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [164]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [165]:
names.sort()
names

array(['Bob', 'Joe', 'Joe', 'Joe', 'Will'], dtype='<U4')

In [166]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 블리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])  #np.in1d(ar,[x,x,x...])

array([ True, False, False,  True,  True, False,  True])

In [167]:
# 배열 데이터의 입출력
ar = np.arange(10)
np.save('some_ar',ar)

In [168]:
np.load('some_ar.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('ar_archive.npz',a=ar,b=ar)

In [170]:
arch = np.load('ar_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
a = np.arange(11,20)  # 인덱스를 표시해줘서 확인하게함 argsort()
print(a,'\n')
np.argsort(a)

[11 12 13 14 15 16 17 18 19] 



array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [172]:
# 인덱스 배열을 역순으로 출력
np.argsort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

### 도전과제(7월6일)-3
- np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
- np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])
```

In [173]:
ar = np.arange(336).reshape(6,7,8)

In [175]:
# Q. 0 ~ 10 정수 (5,5) 행렬의 역행렬을 구한 후 두 행렬간의 행렬곱을 구하세요.
ar = np.random.randint(1,10,size=(5,5))
# np.linalg.inv()  역행렬 구하는 공식
ar2 = np.linalg.inv(ar)
ar2
np.dot(ar,ar2)

array([[ 1.00000000e+00, -1.11022302e-15, -1.11022302e-16,
         0.00000000e+00,  3.88578059e-16],
       [-4.44089210e-16,  1.00000000e+00, -1.11022302e-16,
         0.00000000e+00,  1.11022302e-16],
       [ 0.00000000e+00, -3.33066907e-16,  1.00000000e+00,
         2.22044605e-16,  1.94289029e-16],
       [ 0.00000000e+00, -2.22044605e-16,  5.55111512e-17,
         1.00000000e+00,  2.77555756e-17],
       [-4.44089210e-16, -3.33066907e-16, -5.55111512e-17,
        -2.22044605e-16,  1.00000000e+00]])

### 과제(7월6일) -2
### 아래 가이드에 따라서 고객별 연간 생성하고 아래사항을 수행하세요(관측치 10000개)

#### Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.

거래 번호
- id : 1 ~ 1000번 일련번호 - 개시 후 1만 건의 거래가 있었고 걍 거기에 넘버링한 거라고 이해해보자

고객별 속성 데이터
- cusno : 고객번호 1000개 랜덤
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성

거래 데이터

- product_20 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- product_21 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10,20,30
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- price_21 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- quantity_21 : 1 ~ 100 사이 정수 난수 생성
- amount_20 : price_20 * quantity_20
- amount_21 : price_21 * quantity_21
- sales : 20년 대비 21년구매금액이 증가면 1, 감소면 0

#### Q2. df를 수정하여 5가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요

#### Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.

- 거래일자, 요일, 시간을 10개 추가해서 총 만개의 관측치를 갖는 데이터셋 만드세요.

In [34]:
#Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.
c_id=pd.Series(range(1,1001))
li=list(range(1,1001))
data_id=random.sample(li,1000)
cusno=pd.Series(data_id)
gender=pd.Series(np.random.choice(['male','female'],1000))
age=pd.Series(np.random.randint(1,80,1000))
region=pd.Series(np.random.randint(1,10,1000))
# season = pd.Series(np.radom.choice(['Sp','Su','Fa','Wi'],1000))

product=pd.Series(np.random.choice([10,20,30],10000))
price=pd.Series(np.random.uniform(1000,50000,10000))
quantity=pd.Series(np.random.randint(1,100,10000))

amount = price * quantity
   
cusdf=pd.concat([c_id,cusno,gender,age,region],axis=1)
cuspu=pd.concat([product,price,quantity],axis=1)
#sales : 20년 대비 21년구매금액이 증가면 1, 감소면 0
#cusdf['sales'] = np.where(amount_20<=amount_21,1,0)
cusdf.rename(columns={0:'id',1:'cusno',2:'gender',3:'age',4:'region'},inplace=True)
cuspu.rename(columns={0:'product',1:'price',2:'quantity'},inplace=True)
cusdf.head()

id  cusno  gender  age  region
0   1    767    male   42       5
1   2    789  female   26       5
2   3    117    male   36       7
3   4     36  female    1       8
4   5    409    male   12       7

In [35]:
# 고객별 10개씩 행 추가
cusdf1=cusdf.copy()
for _ in range(9):
    cusdf = cusdf.append(cusdf1.loc[:],ignore_index=True)
cusdf.value_counts('cusno') #10개가 맞는지 확인

C:\Users\admin\AppData\Local\Temp\ipykernel_4840\721968390.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  cusdf = cusdf.append(cusdf1.loc[:],ignore_index=True)


cusno
1       10
672     10
659     10
660     10
661     10
        ..
339     10
340     10
341     10
342     10
1000    10
Length: 1000, dtype: int64

In [36]:
# 고객데이터 구매데이터 합치기
cusdf=pd.concat([cusdf,cuspu],axis=1)
cusdf.head()

id  cusno  gender  age  region  product       price  quantity
0   1    767    male   42       5       30 13900.26164        93
1   2    789  female   26       5       10 12259.80158        47
2   3    117    male   36       7       30 38237.60839        63
3   4     36  female    1       8       30 43519.75759        53
4   5    409    male   12       7       20 38997.60697         7

In [37]:
# 거래일자,요일, 시간을 추가
# 1.data
data_list=list(pd.date_range('2020-01-01','2021-12-31',freq='D'))
cusdf['date']=np.random.choice(data_list,size=10000)

# 2. day(요일)
cusdf['day']=cusdf['date'].apply(lambda x: x.weekday())  # date별 요일을 숫자로
cusdf['day']=cusdf['day'].replace(list(range(7)),['월','화','수','목','금','토','일'])

# 3. 시간
cusdf['time']=np.random.randint(1,25,size=10000)

cusdf.head()

id  cusno  gender  age  region  product       price  quantity       date  \
0   1    767    male   42       5       30 13900.26164        93 2021-12-13   
1   2    789  female   26       5       10 12259.80158        47 2020-03-25   
2   3    117    male   36       7       30 38237.60839        63 2021-11-17   
3   4     36  female    1       8       30 43519.75759        53 2021-12-24   
4   5    409    male   12       7       20 38997.60697         7 2021-02-06   

  day  time  
0   월    16  
1   수    20  
2   수     4  
3   금    14  
4   토    23

In [38]:
# Q2. df를 수정하여 5가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요
# age를 범주화 해서 age_class 컬럼을 새로 추가
def get_age(x):
    if x<20:
        x='미성년'
    elif x<40:
        x='20-30대'
    elif x<60:
        x='40-50대'
    else :
        x='60대이상'
    return x
cusdf['age_class'] = cusdf.age.apply(get_age)
cusdf.head()

id  cusno  gender  age  region  product       price  quantity       date  \
0   1    767    male   42       5       30 13900.26164        93 2021-12-13   
1   2    789  female   26       5       10 12259.80158        47 2020-03-25   
2   3    117    male   36       7       30 38237.60839        63 2021-11-17   
3   4     36  female    1       8       30 43519.75759        53 2021-12-24   
4   5    409    male   12       7       20 38997.60697         7 2021-02-06   

  day  time age_class  
0   월    16    40-50대  
1   수    20    20-30대  
2   수     4    20-30대  
3   금    14       미성년  
4   토    23       미성년

In [39]:
# 불필요한 컬럼 'id, age' 삭제
cusdf2=cusdf.drop(['id','age'],axis=1)

In [41]:
# 인사이트를 추가 하기위해 소비 증가 사용자 함수 'spend' 만들기
def spend(x):
    return x * 1.2
# 연령,성별로 선택하여 소비증가 함수 적용하기
cusdf2.loc[cusdf2['gender']=='female','price'] = cusdf2.loc[cusdf2['gender']=='female','price'].apply(spend)
cusdf2.loc[cusdf2['age_class']=='40-50대','price'] = cusdf2.loc[cusdf2['age_class']=='40-50대','price'].apply(spend)
cusdf2

cusno  gender  region  product       price  quantity       date day  \
0       767    male       5       30 16680.31397        93 2021-12-13   월   
1       789  female       5       10 17654.11427        47 2020-03-25   수   
2       117    male       7       30 38237.60839        63 2021-11-17   수   
3        36  female       8       30 62668.45093        53 2021-12-24   금   
4       409    male       7       20 38997.60697         7 2021-02-06   토   
...     ...     ...     ...      ...         ...       ...        ...  ..   
9995    249    male       5       30 37218.47238        12 2020-06-18   목   
9996    877    male       5       20 44895.60296        77 2020-04-09   목   
9997    970  female       5       30 57550.77357        78 2021-03-27   토   
9998    862    male       1       20  7818.19052        23 2021-03-15   월   
9999    896    male       1       20  1869.23254        26 2021-04-15   목   

      time age_class  
0       16    40-50대  
1       20    20-30대  
2        4    20-30대  
3       14       미성년  
4       23       미성년  
...    ...       ...  
9995     1     60대이상  
9996    18    40-50대  
9997     1       미성년  
9998    11    20-30대  
9999     7       미성년  

[10000 rows x 10 columns]

In [33]:
gend_g2 = cusdf3.get_group('female')
print(gend_g2[['price']].mean())
gend_g3 = cusdf4.get_group('40-50대')
gend_g3[['price']].mean()

price   47583.80754
dtype: float64


price   47583.80754
dtype: float64

## 과제(7월8일) 
- 타이타닉 생존예측률 도출