In [1]:
import numpy as np

In [37]:
# 1,2,3,차원 배열 생성 및 차원 확인
ar1 = np.arange(0,12)
ar2 = np.arange(0,12).reshape(2,6)
ar3 = np.arange(0,12).reshape(2,2,3)

In [38]:
display(ar1)
display(ar2)
display(ar3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [32]:
print(f'{ar1.ndim}차원,{ar2.ndim}차원,{ar3.ndim}차원')

1차원,2차원,3차원


In [33]:
# print(a1.dtype)
a1 = ar1.astype('int32')
a1, a1.dtype

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), dtype('int32'))

#### 과제_0913_1.
- arange, zeros, ones를 배열로 다양하게 생성하세요.

In [72]:
# arange 사용
ar_1 = np.arange(30)
ar_2 = ar_1.reshape(2,15)
ar_3 = ar_1.reshape(3,2,5)
display(ar_1)
display(ar_2)
display(ar_3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [75]:
# zeros 사용
az_1 = np.zeros([30])
az_2 = np.zeros([2,15])
az_3 = np.zeros([3,2,5])
display(az_1)
display(az_2)
display(az_3)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [77]:
# ones 사용
ao_1 = np.ones([30])
ao_2 = np.ones([2,15])
ao_3 = np.ones([3,2,5])
display(ao_1)
display(ao_2)
display(ao_3)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [36]:
# a1으로 1,2,3차원 배열을 만드세요.(reshape)
a1 = np.arange(25)
a1_2 = a1.reshape(5,5)
a1_3 = a1.reshape(5,5,1)
display(a1)
display(a1_2)
display(a1_3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]]])

#### 과제_0913_2
- a1.a2.a3에서 원하는 원소값들을 다양한 방식으로 인덱싱하여 출력하세요.

In [39]:
# 불린 인덱싱
ar1d = np.arange(1,10)
ar1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#  불린 인덱싱으로 6,7,8,9 뽑기
ar = ar1d[ar1d >5]
ar

array([6, 7, 8, 9])

In [48]:
# 일반 인덱싱
indexes = np.array([5,6,7,8])
ar = ar1d[indexes]
ar

array([6, 7, 8, 9])

In [54]:
# 정렬 - np.sort()=(원본 미반영)
# argsort()= 인덱스에 대한 솔트
ar = np.array([3,1,9,5])
s1 = np.sort(ar)
s2 = np.argsort(ar)
display(ar,s1,s2)
# ndarray.sort() 정렬,원본 반영
s1_2 = ar.sort()
display(ar,s1_2)

array([3, 1, 9, 5])

array([1, 3, 5, 9])

array([1, 0, 3, 2], dtype=int64)

array([1, 3, 5, 9])

None

In [56]:
# 내림차순
s1[::-1]

array([9, 5, 3, 1])

#### 과제_0913_3
- ar2d를 로우 방향, 컬럼 방향으로 정렬하세요.

In [116]:
ar2d = np.array([5,2,1,3,4,9,8,6,7]).reshape(3,3)
ar2d

array([[5, 2, 1],
       [3, 4, 9],
       [8, 6, 7]])

In [117]:
ar2d_row = np.sort(ar2d,axis=0)
print(f'로우 방향으로 정렬:')
display(ar2d_row)
ar2d_column = np.sort(ar2d,axis=1)
print(f'컬럼 방향으로 정렬:')
display(ar2d_column)

로우 방향으로 정렬:


array([[3, 2, 1],
       [5, 4, 7],
       [8, 6, 9]])

컬럼 방향으로 정렬:


array([[1, 2, 5],
       [3, 4, 9],
       [6, 7, 8]])

#### 과제_0913_4
- 성적 오름차순으로 이름을 출력하세요.(np.argsort()를 이용)

In [59]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

In [67]:
st = np.argsort(score_array)
st_name = name_array[st]
display(st_name)
display(st_name[::-1])

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

array(['Kate', 'Mike', 'Samuel', 'Sarah', 'John'], dtype='<U6')

In [84]:
# 선형대수 연산 - 행렬 내적
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
dot_product = np.dot(a,b)
display(a)
display(b)
dot_product

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

array([[ 58,  64],
       [139, 154]])

In [85]:
# 전치 행렬
print(a, '\n')
transpose_mat = np.transpose(a)
transpose_mat

[[1 2 3]
 [4 5 6]] 



array([[1, 4],
       [2, 5],
       [3, 6]])

In [204]:
# 40p 부터
import pandas as pd
tdf = pd.read_csv('titanic_train.csv')
tdf.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [90]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [92]:
vcounts = tdf['Pclass'].value_counts()
vcounts

3    491
1    216
2    184
Name: Pclass, dtype: int64

#### 과제_0913_5 (49p)
- 데이터프레임과 리스트, 딕셔너리, ndarray 상호 변환 사례를 작성하여 설명하세요.

In [160]:
# 데이터 프레임(tdf)을 리스트로 
tdf_list=[]
columns=list(tdf.columns.values)
columns
for i in columns:
    tdf_slist = tdf[i].values.tolist()
    tdf_list.append(tdf_slist)

print(tdf_list)

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 2

In [163]:
# 행방향으로 리스트화
tdf_list2=tdf.values.tolist()
tdf_list2_col = np.transpose(tdf_list2)
# 열방향으로 리스트화  (무자형으로 데이터가 리스트됨)
print(tdf_list2_col.tolist())

[['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', 

In [161]:
# 행방향으로 리스트화
tdf_list2=tdf.values.tolist()
# 열방향으로 리스트화
tdf_list2_col = np.transpose(tdf).values.tolist()
tdf_list2_col 
print(tdf_list2_col)

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 2

In [165]:
# 데이터 프레임을 딕셔너리로 변환
tdf_dict = tdf.to_dict('list')
print(tdf_dict)

{'PassengerId': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 2

In [172]:
# 데이터 프레임을 배열로 변환
tdf_array = tdf.values
print(tdf_array)
print('-------------------------------')
# 열방향으로 배열
tdf_array_col = np.transpose(tdf).values
print(tdf_array_col)

[[1 0 3 ... 7.25 nan 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 ...
 [889 0 3 ... 23.45 nan 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 nan 'Q']]
-------------------------------
[[1 2 3 ... 889 890 891]
 [0 1 1 ... 0 1 0]
 [3 1 3 ... 3 1 3]
 ...
 [7.25 71.2833 7.925 ... 23.45 30.0 7.75]
 [nan 'C85' nan ... nan 'C148' nan]
 ['S' 'C' 'S' ... 'S' 'C' 'Q']]


In [176]:
# 리스트 데이터프레임으로 만들기
li_tdf = pd.DataFrame(tdf_list2, columns=columns)
li_tdf

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [178]:
# 배열을 데이터프레임으로 만들기
ar_tdf = pd.DataFrame(tdf_array, columns=columns)
ar_tdf

PassengerId Survived Pclass  \
0             1        0      3   
1             2        1      1   
2             3        1      3   
3             4        1      1   
4             5        0      3   
..          ...      ...    ...   
886         887        0      2   
887         888        1      1   
888         889        0      3   
889         890        1      1   
890         891        0      3   

                                                  Name     Sex   Age SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0     1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0     1   
2                               Heikkinen, Miss. Laina  female  26.0     0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0     1   
4                             Allen, Mr. William Henry    male  35.0     0   
..                                                 ...     ...   ...   ...   
886                              Montvila, Rev. Juozas    male  27.0     0   
887                       Graham, Miss. Margaret Edith  female  19.0     0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN     1   
889                              Behr, Mr. Karl Howell    male  26.0     0   
890                                Dooley, Mr. Patrick    male  32.0     0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171     7.25   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282    7.925   NaN        S  
3       0            113803     53.1  C123        S  
4       0            373450     8.05   NaN        S  
..    ...               ...      ...   ...      ...  
886     0            211536     13.0   NaN        S  
887     0            112053     30.0   B42        S  
888     2        W./C. 6607    23.45   NaN        S  
889     0            111369     30.0  C148        C  
890     0            370376     7.75   NaN        Q  

[891 rows x 12 columns]

In [181]:
# 딕셔너리를 데이터 프레임으로 변환
dict_dtf = pd.DataFrame(tdf_dict)
dict_dtf

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

#### 과제_0913_6
- tdf를 전처리 및 탐색적 분석(시각화, 통계적 기법)을 통하여 분석용 데이터셋으로 만드세요.

In [200]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [201]:
tdf.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [205]:
# 불필요 컬럼 삭제
tdf = pd.read_csv('titanic_train.csv')
tdf1 = tdf.drop(['Cabin'], axis = 1)
tdf1.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [207]:
# family 컬럼 만들기(sibsp+parch)
tdf1['family'] = tdf1['SibSp'] + tdf1['Parch']
tdf1.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  family  
0      0         A/5 21171   7.2500        S       1  
1      0          PC 17599  71.2833        C       1  
2      0  STON/O2. 3101282   7.9250        S       0  
3      0            113803  53.1000        S       1  
4      0            373450   8.0500        S       0

In [213]:
# age null값 채우기
tdf1[tdf1['Age'].isnull()]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Embarked  family  
5      male  NaN      0      0      330877   8.4583        Q       0  
17     male  NaN      0      0      244373  13.0000        S       0  
19   female  NaN      0      0        2649   7.2250        C       0  
26     male  NaN      0      0        2631   7.2250        C       0  
28   female  NaN      0      0      330959   7.8792        Q       0  
..      ...  ...    ...    ...         ...      ...      ...     ...  
859    male  NaN      0      0        2629   7.2292        C       0  
863  female  NaN      8      2    CA. 2343  69.5500        S      10  
868    male  NaN      0      0      345777   9.5000        S       0  
878    male  NaN      0      0      349217   7.8958        S       0  
888  female  NaN      1      2  W./C. 6607  23.4500        S       3  

[177 rows x 12 columns]

In [214]:
pv_age = tdf1.pivot_table(index = ['Survived','Pclass','Sex'],values = ['Age'],aggfunc= ['mean','max','min','std']).round()
pv_age

mean   max   min   std
                         Age   Age   Age   Age
Survived Pclass Sex                           
0        1      female  26.0  50.0   2.0  24.0
                male    45.0  71.0  18.0  14.0
         2      female  36.0  57.0  24.0  13.0
                male    33.0  70.0  16.0  12.0
         3      female  24.0  48.0   2.0  13.0
                male    27.0  74.0   1.0  12.0
1        1      female  35.0  63.0  14.0  13.0
                male    36.0  80.0   1.0  15.0
         2      female  28.0  55.0   2.0  13.0
                male    16.0  62.0   1.0  20.0
         3      female  19.0  63.0   1.0  12.0
                male    22.0  45.0   0.0  12.0

In [216]:
display(tdf1[(tdf1['Survived']==0)&(tdf1['Pclass']==1)&(tdf1['Sex']=='male')])


PassengerId  Survived  Pclass                                  Name  \
6              7         0       1               McCarthy, Mr. Timothy J   
27            28         0       1        Fortune, Mr. Charles Alexander   
30            31         0       1              Uruchurtu, Don. Manuel E   
34            35         0       1               Meyer, Mr. Edgar Joseph   
35            36         0       1        Holverson, Mr. Alexander Oskar   
..           ...       ...     ...                                   ...   
806          807         0       1                Andrews, Mr. Thomas Jr   
815          816         0       1                      Fry, Mr. Richard   
822          823         0       1       Reuchlin, Jonkheer. John George   
867          868         0       1  Roebling, Mr. Washington Augustus II   
872          873         0       1              Carlsson, Mr. Frans Olof   

      Sex   Age  SibSp  Parch    Ticket      Fare Embarked  family  
6    male  54.0      0      0     17463   51.8625        S       0  
27   male  19.0      3      2     19950  263.0000        S       5  
30   male  40.0      0      0  PC 17601   27.7208        C       0  
34   male  28.0      1      0  PC 17604   82.1708        C       1  
35   male  42.0      1      0    113789   52.0000        S       1  
..    ...   ...    ...    ...       ...       ...      ...     ...  
806  male  39.0      0      0    112050    0.0000        S       0  
815  male   NaN      0      0    112058    0.0000        S       0  
822  male  38.0      0      0     19972    0.0000        S       0  
867  male  31.0      0      0  PC 17590   50.4958        S       0  
872  male  33.0      0      0       695    5.0000        S       0  

[77 rows x 12 columns]

## 사이킷런을 이용하여 붗꽃(iris) 데이터 품종 예측하기 86p

In [218]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [102]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [104]:
iris_data = iris.data
iris_label = iris.target
print(iris.feature_names,'\n')
print(iris.target_names,'\n')
print(iris_data,'\n')
print(iris_label)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] 

['setosa' 'versicolor' 'virginica'] 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5

In [105]:
idf = pd.DataFrame(iris_data, columns=iris.feature_names)
idf['label'] = iris.target
idf.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

#### 과제_0913_7
- idf에 학습용, 평가용 데이터를 8:2로 나누어서 분류 모델링(dt) 및 정확도 평가를 수행하세요

In [221]:
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                   test_size=0.2)

In [222]:
dt_clf = DecisionTreeClassifier()

In [223]:
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [224]:
pred = dt_clf.predict(x_test)

In [228]:
from sklearn.metrics import accuracy_score
print('예측정확도: {0:4f}'.format(accuracy_score(y_test,pred)))

예측정확도: 0.966667
